# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9474ac6034c11cb325cdc5b75279adbf789f46581ef0ea645f0e64925ba2f69386b9312f95d5849588968558c38a3430c4b501243458423f8bc666142566181e

test:
  secret_key_base: ee2a5b08a16f3a6acfc76b44eaf8802008acf573855dab9cd39fb21ad1c58e3eb8392ab1c0b16d7dc7164dbc6a7afcae42676faacbb0980ca730c296de7854d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
